### ISSUE TITLE
[12.0][CE] Location completion empty after select a value

### ISSUE THREAD

**Issue by josepmy** [OCA/partner-contact#762] opened 2019-08-08 15:24 UTC
Steps to reproduce it:

1. Create a new customer
2. Search a city or zip code in "location completion" and select it.
3. Customers fields are filled correctly.
4. Delete the "location completion" value and find another value. The list is empty.
5. Delete values of city, address, zip, state and country.
6. Try to find another value in "location completion". The list is empty.

To get new values you must cancel and start a new one customer registration.

Salut,
Josep M

**Comment by GSLabIt** [comment] 2019-10-10 19:51
I'm facing the same issue, any hint? See video: https://recordit.co/5Sk5bF0sm5

**Comment by josepmy** [comment] 2019-10-11 06:21
Still the same issue. I have a change made to test it but I need check it.

**Comment by GSLabIt** [comment] 2019-10-11 06:45
@pedrobaeza is that by design?

**Comment by robin5210** [comment] 2019-10-15 08:47
I also encounter the same problem. A fix to me seems to add the following 2 lines of code in models/res_partner.py in the _onchange_zip_id method after the main if.

```  python     
else:
    self.city_id = False
```

I'm not sure this fix breaks something else.

**Comment by josepmy** [comment] 2019-10-15 09:38
Yes, I have the same fix to test.

**Comment by pedrobaeza** [comment] 2019-10-15 17:05
Fixed in 64aaafa45c022116084675e6181d338a8c386f83

**Closed as completed by pedrobaeza** 2019-10-15 17:05 UTC
