### ISSUE TITLE
Not possible to import/add in/to Odoo online

### ISSUE THREAD

**Issue by TechAndris** [OCA/partner-contact#920] opened 2020-05-24 10:08 UTC
module: partner_firstname
version: 13.0

**Steps to reproduce**
- Create new db with Studio app 
- Activate developer mode
- Go to Apps and chose Import Module
- Import downloaded App (partner_firstname) archive

**Current behavior**
It gives you the following error message:
Error while importing module 'partner_firstname'.

 Error while validating view

Field `partner_names_order` does not exist

Error context:
View `Add partner_names_order config parameter`
[view_id: 1000, xml_id: n/a, model: res.config.settings, parent_id: 266]
None
<odoo>

     <record id="res_config_settings_view_form" model="ir.ui.view">
        <field name="name">Add partner_names_order config parameter</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="base_setup.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <xpath expr="//div[@id='companies']" position="after">
                <h2>Partner Names Order</h2>
                <div class="row mt16 o_settings_container" name="partner_names_order">
                    <div class="col-xs-12 col-md-6 o_setting_box">
                        <div class="o_setting_right_pane">
                            <field name="partner_names_order"/>
                            <field name="partner_names_order_changed" invisible="1"/>
                            <button name="action_recalculate_partners_name" string="Recalculate names" icon="fa-play" type="object" help="Recalculate names for all partners. This process could take so much time if there are more than 10,000 active partners" attrs="{'invisible': [('partner_names_order_changed', '=', False)]}"/>
                        </div>
                    </div>
                </div>
            </xpath>
        </field>
    </record>

</odoo>
/tmp/tmpcu3cbjlp/partner_firstname/views/base_config_view.xml
4 
 Make sure those modules are installed and try again.

**Expected behavior**
module is installed

**Comment by pedrobaeza** [comment] 2020-05-24 10:31
The module is working, as you can try on runbot on the button in the README.

The problem is with your deployment, as Odoo online doesn't allow to add extra modules (odoo.sh does), so closing due to this. Import option is only for data module.

**Closed as completed by pedrobaeza** 2020-05-24 10:31 UTC
